
use std::path::{Path, PathBuf};

use crate::extract::Module;

pub fn rewrite_require(expr: &str) -> String {
    if expr == "script" || expr.starts_with("script.") {
        format!("script.Parent{}", &expr["script".len()..])
    } else {
        expr.to_string()
    }
}

fn cites(texts: &[String], name: &str) -> bool {
    texts.iter().any(|t| has_word(t, name))
}

fn has_word(text: &str, name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let bytes = text.as_bytes();
    let target = name.as_bytes();
    let is_word_byte = |b: u8| b.is_ascii_alphanumeric() || b == b'_';

    let mut i = 0;
    while let Some(pos) = text[i..].find(name) {
        let start_at = i + pos;
        let end_at = start_at + target.len();
        let before_ok = start_at == 0 || !is_word_byte(bytes[start_at - 1]);
        let after_ok = end_at >= bytes.len() || !is_word_byte(bytes[end_at]);
        if before_ok && after_ok {
            return true;
        }
        i = start_at + 1;
        if i >= text.len() {
            break;
        }
    }
    false
}

fn cites_alias(texts: &[String], alias: &str) -> bool {
    texts.iter().any(|t| {
        let mut i = 0;
        while let Some(pos) = t[i..].find(alias) {
            let start_at = i + pos;
            let end_at = start_at + alias.len();
            let before_ok = start_at == 0 || !t.as_bytes()[start_at - 1].is_ascii_alphanumeric();
            let after = t[end_at..].trim_start();
            if before_ok && after.starts_with('.') {
                return true;
            }
            i = start_at + 1;
            if i >= t.len() {
                break;
            }
        }
        false
    })
}

pub fn leaf_path(origin: &Path) -> PathBuf {
    origin.parent().unwrap_or(Path::new(".")).join("Type.luau")
}

pub fn emit(m: &Module) -> String {
    let mut members: Vec<(String, String)> = m
        .fields
        .iter()
        .map(|c| (c.name.clone(), c.ty.clone()))
        .collect();
    members.extend(m.methods.iter().map(|x| (x.name.clone(), x.signature.clone())));
    let texts: Vec<String> = members.iter().map(|(_, t)| t.clone()).collect();

    let requires: Vec<_> = m.requires.iter().filter(|r| cites_alias(&texts, &r.alias)).collect();

    let mut locals = Vec::new();
    let mut stale: Vec<_> = m.local_types.iter().collect();
    let mut target = texts.clone();
    loop {
        let before = locals.len();
        let mut rest = Vec::new();
        for tl in stale {
            if cites(&target, &tl.name) {
                target.push(tl.text.clone());
                locals.push(tl);
            } else {
                rest.push(tl);
            }
        }
        stale = rest;
        if locals.len() == before {
            break;
        }
    }

    let exprs: Vec<String> = requires.iter().map(|r| rewrite_require(&r.expr)).collect();
    let services: Vec<_> = m
        .services
        .iter()
        .filter(|s| exprs.iter().any(|e| e.starts_with(&format!("{}.", s.alias))))
        .collect();

    let mut blocks = vec![format!(
        "--!strict\n\
         -- GENERATED by modux from {}\n\
         -- DO NOT EDIT: the next generation overwrites this file.\n",
        m.file
    )];

    let mut header = Vec::new();
    for s in &services {
        header.push(format!(
            "local {} = game:GetService(\"{}\")",
            s.alias, s.service
        ));
    }
    for (i, r) in requires.iter().enumerate() {
        header.push(format!("local {} = require({})", r.alias, exprs[i]));
    }
    if !header.is_empty() {
        blocks.push(format!("{}\n", header.join("\n")));
    }

    if !locals.is_empty() {
        let copied: Vec<&str> = locals.iter().map(|t| t.text.as_str()).collect();
        blocks.push(format!("{}\n", copied.join("\n")));
    }

    let mut body = vec!["export type Public = {".to_string()];
    for (name, ty) in &members {
        body.push(format!("\t{name}: {ty},"));
    }
    body.push("}".to_string());
    blocks.push(format!("{}\n", body.join("\n")));

    blocks.push("return {}\n".to_string());
    blocks.join("\n")
}
