
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{bail, Result};

use crate::extract::Module;
use crate::rojo::{Side, Map};


pub const TARGETS: [(Side, &str); 2] = [
    (Side::Client, "src/Modux/client/Manifest/init.luau"),
    (Side::Server, "src/Modux/server/Manifest/init.luau"),
];

pub const MODULE_LISTS: [(Side, &str); 2] = [
    (Side::Client, "src/Modux/client/Modules.luau"),
    (Side::Server, "src/Modux/server/Modules.luau"),
];

fn buckets(side: Side) -> &'static [(&'static str, &'static str)] {
    match side {
        Side::Client => &[("Controller", "AllControllers"), ("Component", "AllComponents")],
        Side::Server => &[("Service", "AllServices"), ("Component", "AllComponents")],
        Side::Shared => &[],
    }
}

pub fn targets(root: &Path) -> Vec<(Side, PathBuf)> {
    TARGETS.iter().map(|(l, p)| (*l, root.join(p))).collect()
}

pub fn module_lists(root: &Path) -> Vec<(Side, PathBuf)> {
    MODULE_LISTS.iter().map(|(l, p)| (*l, root.join(p))).collect()
}

pub fn validate(modules: &[Module], map: &Map) -> Result<BTreeMap<String, Side>> {
    let mut by_id: BTreeMap<&str, &Module> = BTreeMap::new();
    for m in modules {
        if let Some(previous) = by_id.insert(m.id.as_str(), m) {
            bail!("duplicate ID {:?} in {} and {}", m.id, previous.file, m.file);
        }
    }

    let mut sides: BTreeMap<String, Side> = BTreeMap::new();
    for m in modules {
        sides.insert(m.id.clone(), map.side(Path::new(&m.file))?);
    }

    for m in modules {
        let mine = sides[&m.id];
        for dep in &m.declared_require {
            let Some(target) = by_id.get(dep.as_str()) else {
                let available: Vec<&str> = by_id.keys().copied().collect();
                bail!(
                    "[Manifest] {} requires {:?}, which does not exist. Available: {}",
                    m.file,
                    dep,
                    available.join(", ")
                );
            };
            let theirs = sides[dep.as_str()];
            if !mine.sees(theirs) {
                bail!(
                    "[Manifest] {} is {} and requires {:?}, which is {}.\n  \
                     {} cannot see {} — move one of them, or go through the network.\n  \
                     ({} is in {})",
                    m.file,
                    mine.name(),
                    dep,
                    theirs.name(),
                    mine.name(),
                    theirs.name(),
                    dep,
                    target.file
                );
            }
        }
    }

    Ok(sides)
}

pub fn emit(
    side: Side,
    modules: &[Module],
    sides: &BTreeMap<String, Side>,
    map: &Map,
) -> Result<Option<String>> {
    let visible: Vec<&Module> = modules
        .iter()
        .filter(|m| side.sees(sides[&m.id]))
        .collect();

    let own_side: Vec<&&Module> = visible.iter().filter(|m| sides[&m.id] == side).collect();
    if own_side.is_empty() && visible.is_empty() {
        return Ok(None);
    }

    let mut blocks = vec![format!(
        "--!strict\n\
         -- GENERATED by modux. DO NOT EDIT: the next generation overwrites this file.\n\
         -- Manifest for the {} side.\n",
        side.name()
    )];

    let mut paths = vec![
    ];
    for m in &visible {
        let leaf = crate::emit::leaf_path(Path::new(&m.file));
        paths.push((m.id.clone(), map.path(&leaf)?));
    }

    let mut roots: Vec<String> = Vec::new();
    for (_, path) in &paths {
        let root = path.split('.').next().unwrap_or_default().to_string();
        if !root.is_empty() && !roots.contains(&root) {
            roots.push(root);
        }
    }
    roots.sort();

    let mut requires: Vec<String> = roots
        .iter()
        .map(|r| format!("local {r} = game:GetService(\"{r}\")"))
        .collect();
    for (alias, path) in &paths {
        requires.push(format!("local {alias} = require({path})"));
    }
    blocks.push(format!("{}\n", requires.join("\n")));

    for (kind, alias) in buckets(side) {
        let of_kind: Vec<&&Module> = visible.iter().filter(|m| m.kind == *kind).collect();
        if of_kind.is_empty() {
            blocks.push(format!("export type {alias} = {{}}\n"));
            continue;
        }
        let mut body = vec![format!("export type {alias} = {{")];
        for m in of_kind {
            body.push(format!("\t{}: {},", m.id, entry(m)));
        }
        body.push("}".to_string());
        blocks.push(format!("{}\n", body.join("\n")));
    }

    blocks.push(component_access(&visible));

    blocks.push("return {}\n".to_string());
    Ok(Some(blocks.join("\n")))
}

// One concrete entry per component, rather than a generic
// `GetComponent<CID>(id: CID, ...) -> index<AllComponents, CID>`.
//
// That generic form does typecheck on its own, but it has to reach the module
// author through the extras of `SelfOf.Build`, and a generic function there
// stops the type function from reducing. It does not error: `Build<...>` simply
// stays unevaluated, and the symptom lands somewhere else entirely, as
// `Cannot add property 'Whatever' to table 'setmetatable<Build<...>, ...>'` on
// a method declaration that was fine a moment ago.
//
// Writing the table out per component keeps the lookup by key with no generic
// anywhere, which is work this generator is here to do.
fn component_access(visible: &[&Module]) -> String {
    let components: Vec<&&Module> = visible.iter().filter(|m| m.kind == "Component").collect();
    if components.is_empty() {
        return "export type ComponentAccess = {}\n".to_string();
    }

    let mut body = vec!["export type ComponentAccess = {".to_string()];
    for m in components {
        let public = entry(m);
        body.push(format!("\t{}: {{", m.id));
        body.push(format!(
            "\t\tGet: (self: any, instance: Instance) -> {public}?,"
        ));
        body.push(format!(
            "\t\tCreate: (self: any, instance: Instance) -> {public},"
        ));
        body.push(format!("\t\tAll: (self: any) -> {{ {public} }},"));
        body.push("\t},".to_string());
    }
    body.push("}".to_string());
    format!("{}\n", body.join("\n"))
}

fn entry(m: &Module) -> String {
    format!("{}.Public", m.id)
}

pub fn emit_module_list(
    side: Side,
    modules: &[Module],
    sides: &BTreeMap<String, Side>,
    map: &Map,
) -> Result<Option<String>> {
    let visible: Vec<&Module> = modules.iter().filter(|m| side.sees(sides[&m.id])).collect();
    if visible.is_empty() {
        return Ok(None);
    }

    let mut paths = Vec::new();
    for m in &visible {
        paths.push(map.path(Path::new(&m.file))?);
    }

    let mut roots: Vec<String> = Vec::new();
    for path in &paths {
        let root = path.split('.').next().unwrap_or_default().to_string();
        if !root.is_empty() && !roots.contains(&root) {
            roots.push(root);
        }
    }
    roots.sort();

    let mut out = format!(
        "--!strict\n\
         -- GENERATED by modux. DO NOT EDIT: the next generation overwrites this file.\n\
         -- Instance list of every Modux module on the {} side. No requires here:\n\
         -- requiring the bodies from a module the bodies require would close a cycle.\n\n",
        side.name()
    );
    for r in &roots {
        out.push_str(&format!("local {r} = game:GetService(\"{r}\")\n"));
    }
    out.push_str("\nreturn {\n");
    for path in &paths {
        out.push_str(&format!("\t{path},\n"));
    }
    out.push_str("} :: { ModuleScript }\n");
    Ok(Some(out))
}
